language: ruby
rvm:
  - ree
  - 1.8.7
  - 1.9.3
  - jruby-18mode
  - jruby-19mode
before_install:
  - sudo apt-get install libraptor2-0
  - sudo ln -s /usr/lib/libraptor2.so.0 /usr/lib/libraptor2.so
bundler_args: --without development