language: ruby
rvm:
  - ree
  - 1.8.7
  - 1.9.3
  - jruby-18mode # JRuby in 1.8 mode
  - jruby-19mode # JRuby in 1.9 mode
  - rbx-18mode
  - rbx-19mode
before_install:
  - sudo apt-get install libraptor2-0
  - sudo ln -s /usr/lib/libraptor2.so.0 /usr/lib/libraptor2.so
