language: ruby
bundler_args: --without debug
script: "bundle exec rspec spec"
env:
  - CI=true
rvm:
  - 2.2
  - 2.3
  - 2.4
  - jruby-9
  - rbx-3
matrix:
  allow_failures:
    - rvm: rbx-3
addons:
  apt:
    packages:
      - raptor2-utils
cache: bundler
sudo: false
