language: ruby
bundler_args: --without debug
script: "bundle exec rspec spec"
env:
  - CI=true
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - jruby-19mode
  - rbx-2
matrix:
  allow_failures:
    - rvm: rbx-2
before_install:
  - sudo apt-get install libraptor2-0
cache: bundler
